### ISSUE TITLE
store fails without full / absolute path

### ISSUE THREAD

**Issue by finoradin** [filecoin-project/starling#26]
It is standard behavior for CLI apps to accept both relative and absolute paths, but the current implementation does not.

Steps to reproduce:
1. let's say my `pwd` is my home folder `~/` and that in my home folder there is a file called `foobar.txt`
2. `starling store foobar.txt`
3. storage will fail with "🚫 Error: open another-readme.txt-encrypted: no such file or directory"
4. `starling store ~/foobar.txt`
5. it works!

relative paths should work…

**Comment by alexandrumatei36** [comment]
This behaviour is inherited from the previous version. We'll improve this aspect
