### ISSUE TITLE
Couldn't connect to Lotus

### ISSUE THREAD

**Issue by MeijeSibbel** [filecoin-project/starling#54]
I haven't been able to upload through Starling with the latest lotus release and am prompted with the following error: 
```                                                                       
Finding minersCouldn't connect to Lotus
Couldn't connect to Lotus
Couldn't connect to Lotus
Couldn't connect to Lotus
Couldn't connect to Lotus
```
Exports have been set as per documentation:
```
export LOTUS_URL="ws://127.0.0.1/1234/rpc/v0"
export LOTUS_AUTH_TOKEN=eyJhbGciOiJIUzI1NiIsI...
```

**Comment by alexandrumatei36** [comment]
Maybe LOTUS_URL should not have quotation marks

**Comment by alexandrumatei36** [comment]
Starling has been updated to rely on the local Lotus configuration. Setting ENV vars is not required anymore
